server:
  port: 8080
  use-forward-headers: true
  servlet:
    session:
      timeout: 86400
spring:
  transaction:
    rollback-on-commit-failure: true
  #druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySql配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sensboot?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: ${mysql.username:root}
    password: ${mysql.password:123456}
    filters: stat
    initialSize: 100
    maxActive: 1000
    maxOpenPreparedStatements: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 500
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: select 'x'
  # redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    timeout: 5000

  # thymeleaf
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

# 因为下面配了多数据源配置，可以注释此处
# mybatis plus
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.liuyanzhao.sens.entity
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #逻辑删除配置（下面3个配置）
#    logic-delete-value: 0
#    logic-not-delete-value: 1
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: true

# 日志
logging:
  file: ./logs/log.log
  level:
    org:
      springframework:
        boot:
          autoconfigure: error
application:
  formatted-version: 1.0.0

user:
  import:
    max: 1000




# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true


# 测试多数据源 ===>
db1:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/sensboot?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
  username: root
  password: 123456
  initialSize: 5
  minIdle: 5
  maxActive: 50

db2:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1:3306/sensboot
  username: root
  password: 123456
  platform: postgres
  initialSize: 5
  minIdle: 5
  maxActive: 50
# <=== 测试多数据源

